spring: 
  profiles:
    active:
      dev

---
spring:
  profiles: dev
  application:
    name: springcloud-config-client-3355-dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-client-3355-test    
