spring: 
  profiles:
    active:
      dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-config-client-3355
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-config-client-3355
